### ISSUE TITLE
where i can see the demo

### ISSUE THREAD

**Issue by OrangeSAM** [Bug-Duck/vuemotion#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sheepbox8646** [comment]
The projects is developing so we have no demo current, please wait for a month, thanks for understanding. you also can watch the demos of the projects' last generation, it's [Newcar](https://github.com/dromara/newcar)
